
services:
  - type: web
    name: gptbots
    env: python
    buildCommand: "pip install --upgrade pip && pip install git+https://github.com/Rapptz/discord.py && pip install -r requirements.txt"
    startCommand: "gunicorn app"
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false 
      - key: CHAT_GPT_SESSION_TOKEN
        sync: false 
      - key: OPENAI_API_KEY
        sync: false
      - fromGroup: GPTBotEnvs
      - key: PYTHON_VERSION
        value: 3.8.2

envVarGroups:
  - name: GPTBotEnvs
    envVars:
      - key: CHAT_GPT_SESSION_TOKEN
        sync: false
      - key: DISCORD_BOT_TOKEN
        sync: false
